[package]
name = "metaboss_lib"
version = "0.1.0"
edition = "2021"
description = "The core library for the metaboss cli."
repository = "https://github.com/samuelvanderwaal/metaboss_lib"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
borsh = "0.9.3"
# mpl-token-auth-rules = { version = "1.0.0", features = ["no-entrypoint"] }
mpl-token-auth-rules = { path = "/home/cilantro/Metaplex/mpl-token-auth-rules/program", features = ["no-entrypoint", "feature1", "feature2"] }
mpl-token-metadata = { version = "1.7.0", features = ["no-entrypoint", "serde-feature"] }
retry = "1.3.0"
rmp-serde = "1.1.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
solana-account-decoder = "1.10"
solana-client = "1.10"
solana-program = "1.10"
solana-sdk = "1.10"
spl-associated-token-account = "1.1"
spl-token = "3.2.0"
thiserror = "1.0.30"
